const NodeType = {
  SUPPLIER: 'SUPPLIER',
  WAREHOUSE: 'WAREHOUSE',
  DISTRIBUTION_CENTER: 'DISTRIBUTION_CENTER',
  RETAILER: 'RETAILER',
};

const DisruptionType = {
  SUPPLIER_FAILURE: 'SUPPLIER_FAILURE',
  NODE_OUTAGE: 'NODE_OUTAGE',
  EDGE_BLOCKAGE: 'EDGE_BLOCKAGE',
  DELAY: 'DELAY',
};

const EventType = {
  DISRUPTION_ACTIVATED: 'DISRUPTION_ACTIVATED',
  DISRUPTION_RESOLVED: 'DISRUPTION_RESOLVED',
  SHIPMENT_DISPATCHED: 'SHIPMENT_DISPATCHED',
  SHIPMENT_ARRIVED: 'SHIPMENT_ARRIVED',
  ORDER_FULFILLED: 'ORDER_FULFILLED',
  ORDER_DELAYED: 'ORDER_DELAYED',
  STOCKOUT_OCCURRED: 'STOCKOUT_OCCURRED',
};

module.exports = {
  NodeType,
  DisruptionType,
  EventType,
};
